### ISSUE TITLE
Hack Series Facilitators

### ISSUE THREAD

**Issue by paked** [hackclub/meta#408] opened 2015-12-15 17:43 UTC
We're going to be running 10 different cohorts on Friday, Saturday and Sunday. In order to fill up the weekend sessions, we're going to need extra leaders.

It was agreed we would try pulling some leaders from our prospective applicant pool (which @zachlatta is also working through today, #311)

Alex and Selynna have both confirmed that they are going to take a cohort on the weekend. Alex has not specified a time, Selynna is going to do 4pm.

**Comment by jonleung** [comment] 2015-12-17 23:08
This is who have confirmed they _can_ lead the sessions:

**Friday**
- Jonathan Leung

**Saturday (all sessions)**
- Issa
- @ssun098 

**Sunday**
- Erina
- Jasmine
- Leila

I will be chatting with Alex B and and other Alex later

**Comment by zachlatta** [comment] 2015-12-18 06:02
Can we close this? Seems like we have people set.

**Comment by paked** [comment] 2015-12-18 07:17
@zachlatta Looks like we are still waiting on time slots from Alex *'s

**Comment by zachlatta** [comment] 2015-12-18 12:24
Ah, sounds good!

**Comment by MaxWofford** [comment] 2015-12-21 14:19
Closing this because Hack Series is done. Kudos to the awesome volunteer facilitators we had. 

![](http://quickme.me/success.gif)

**Closed by MaxWofford** 2015-12-21 14:19 UTC
